### ISSUE TITLE
Erro ao executar com Schema Normal

### ISSUE THREAD

**Issue by benevides** [turicas/socios-brasil#26]
Ao tenta executar o comando 
`rows pgimport --schema=schema/empresa.csv data/output/empresa.csv.gz $POSTGRESQL_URI empresa`
Apresenta o seguinte erro.
Importing data: 9.39Gbytes [02:08, 73.2Mbytes/s]Traceback (most recent call last):                                                                                                                            
  File "/home/benevides/.local/bin/rows", line 10, in <module>
    sys.exit(cli())
  File "/home/benevides/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/benevides/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/benevides/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/benevides/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/benevides/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/benevides/.local/lib/python3.7/site-packages/rows/cli.py", line 749, in command_pgimport
    schema=schemas[0],
  File "/home/benevides/.local/lib/python3.7/site-packages/rows/utils.py", line 938, in pgimport
    raise RuntimeError(stderr.decode("utf-8"))
RuntimeError: ERROR:  extra data after last expected column
CONTEXT:  COPY empresa, line 2: "00000000000191,1,BANCO DO BRASIL SA,DIRECAO GERAL,2,2005-11-03,0,,,,2038,1966-08-01,6422100,QUADRA,"..."

**Comment by turicas** [comment]
- A tabela `empresa` existia antes de você rodar esse comando?
- O arquivo `data/output/empresa.csv.gz` é o "sem censura"? Se for, você deve usar o `schema-full/empresa.csv`.

**Comment by benevides** [comment]
> * A tabela `empresa` existia antes de você rodar esse comando?
> * O arquivo `data/output/empresa.csv.gz` é o "sem censura"? Se for, você deve usar o `schema-full/empresa.csv`.

Obrigado, eu gerei os arquivos novamente e funcionou.
Gostaria de saber por que o número do CPF aparece com *** entre os números.

Grato

**Comment by turicas** [comment]
A Receita Federal libera os dados assim para não expor o CPF completo dos sócios.
