### ISSUE TITLE
Erro ao executar com Schema FULL

### ISSUE THREAD

**Issue by benevides** [turicas/socios-brasil#27]
Ao tentar executar o comando usando o schema full
`rows pgimport --schema=schema-full/empresa.csv data/output/empresa.csv.gz $POSTGRESQL_URI empresa`
Apresenta o seguinte erro.
Traceback (most recent call last):
  File "/home/benevides/.local/lib/python3.7/site-packages/rows/utils.py", line 931, in pgimport
    written = process.stdin.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/benevides/.local/bin/rows", line 10, in <module>
    sys.exit(cli())
  File "/home/benevides/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/benevides/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/benevides/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/benevides/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/benevides/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/benevides/.local/lib/python3.7/site-packages/rows/cli.py", line 749, in command_pgimport
    schema=schemas[0],
  File "/home/benevides/.local/lib/python3.7/site-packages/rows/utils.py", line 947, in pgimport
    raise RuntimeError(process.stderr.read().decode("utf-8"))
RuntimeError: ERROR:  column "codigo_pais" of relation "empresa" does not exist

**Comment by turicas** [comment]
Provavelmente você já tinha criado a tabela antes com o schema mais simples. Experimente deletar a tabela `empresa` e rodar novamente esse comando.

**Comment by benevides** [comment]
> Provavelmente você já tinha criado a tabela antes com o schema mais simples. Experimente deletar a tabela `empresa` e rodar novamente esse comando.

Obrigado
