### ISSUE TITLE
Erro ao executar o schema FULL - broken pipe e unquoted carrier

### ISSUE THREAD

**Issue by gpompeo** [turicas/socios-brasil#28]
Olá, ao executar a importacao para o psql com o schema full, recebo o seguinte erro:

$ rows pgimport --schema=schema-full/empresa.csv data/output/empresa.csv.gz $POSTGRESQL_URI empresa
Importing data: 4.68Gbytes [00:39, 117Mbytes/s]Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\rows\utils.py", line 931, in pgimport
    written = process.stdin.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\rows.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\rows\cli.py", line 749, in command_pgimport
    schema=schemas[0],
  File "c:\programdata\anaconda3\lib\site-packages\rows\utils.py", line 947, in pgimport
    raise RuntimeError(process.stderr.read().decode("utf-8"))
RuntimeError: ERROR:  unquoted carriage return found in data
HINT:  Use quoted CSV field to represent carriage return.
CONTEXT:  COPY empresa, line 264

Eu já verifiquei que não tinha a tabela empresa criada. O que mais pode estar gerando o erro?

**Comment by gpompeo** [comment]
Não sei se está relacionado, mas também tenho o erro abaixo ao rodar o comando: 

time python extract_partner_companies.py data/output/socio.csv.gz data/output/empresa-socia.csv.gz

Erro:

Traceback (most recent call last):
  File "extract_partner_companies.py", line 31, in <module>
    lambda row: row["identificador_de_socio"] == "1",
  File "extract_partner_companies.py", line 15, in filter_csv
    for row in csv_reader:
  File "C:\ProgramData\Anaconda3\lib\site-packages\tqdm\_tqdm.py", line 931, in __iter__
    for obj in iterable:
  File "C:\ProgramData\Anaconda3\lib\csv.py", line 119, in __next__
    row = next(self.reader)
  File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3141: character maps to <undefined>

**Comment by turicas** [comment]
Qual sua versão da rows instalada? Teste com a versão do `develop` atual:

    pip install https://github.com/turicas/rows/archive/develop.zip

Caso ainda assim não funcione, vou precisar de mais detalhes (como não uso Windows, pode ser que exista algum problema dela).

**Comment by gpompeo** [comment]
eu estava usando a versao 0.4.2.dev0 que é a mesma que está no comando acima.

será que o erro no script do extract_partner_company pode estar influenciando?

**Comment by gpompeo** [comment]
Atualizando, alterei a linha #9 do extract_partner_companies e este script rodou. Segue como ficou a linha 9:

    fobj_reader = open_compressed(input_filename, mode="r", encoding='UTF-8')

Todavia, ainda assim o comando inicial para importar para o postgre deu o mesmo erro.

Que tipo de informações adicionais você necessita?

**Comment by gpompeo** [comment]
Realmente não consegui fazer funcionar pelo Windows, todavia tive sucesso rodando pelo Linux.
