### ISSUE TITLE
run.sh: KeyError: 'cnpj_cpf_do_socio'

### ISSUE THREAD

**Issue by cemsbr** [turicas/socios-brasil#30]
Depois do download, aparece:
```
Extracting data/download/DADOS_ABERTOS_CNPJ_01.zip: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "extract_dump.py", line 392, in <module>
    main()
  File "extract_dump.py", line 387, in main
    censorship=censorship,
  File "extract_dump.py", line 316, in extract_files
    data = transform_functions[row_type](row)
  File "extract_dump.py", line 197, in transform_socio
    if row["cnpj_cpf_do_socio"] == "000***000000**":
KeyError: 'cnpj_cpf_do_socio'
```

**Comment by cemsbr** [comment]
Funcionou após instalar as dependências pelo requirements.txt. Acho que o problema foi instalar a versão do rows que está no Pypi.

**Comment by turicas** [comment]
Lembrando que você pode baixar a versão já convertida dos dados, para não precisar rodar o script. Mais detalhes [nessa thread](https://twitter.com/turicas/status/1161966784083369984).
