### ISSUE TITLE
Falha na hora de importar: No such file or directory: 'psql': 'psql'

### ISSUE THREAD

**Issue by kokoroko2** [turicas/socios-brasil#32]
Alguém enfrentando algo parecido? (tirei da msg de erro só os dados de acesso so postgresql)
Consigo me conectar normalmente ao banco por essa máquina.
```
kokoroko@laura:~/socios-brasil$ sudo rows pgimport --schema=schema/empresa.csv data/output/empresa.csv.gz $POSTGRESQL_URI empresa
Reading schema:   0%|                                                                                                                                                                                         | 0.00/1.00G [00:00<?, ?bytes/s]Traceback (most recent call last):
  File "/home/kokoroko/.local/lib/python3.6/site-packages/rows/utils.py", line 728, in execute_command
    stderr=subprocess.PIPE,
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'psql': 'psql'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/rows", line 11, in <module>
    load_entry_point('rows==0.4.2.dev0', 'console_scripts', 'rows')()
  File "/home/kokoroko/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kokoroko/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kokoroko/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kokoroko/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kokoroko/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/kokoroko/.local/lib/python3.6/site-packages/rows/cli.py", line 840, in command_pgimport
    schema=schemas[0],
  File "/home/kokoroko/.local/lib/python3.6/site-packages/rows/utils.py", line 929, in pgimport
    execute_command(get_psql_command(create_table, database_uri=database_uri))
  File "/home/kokoroko/.local/lib/python3.6/site-packages/rows/utils.py", line 731, in execute_command
    raise RuntimeError("Command not found: {}".format(repr(command)))
RuntimeError: Command not found: ['psql', '-c', 'CREATE TABLE IF NOT EXISTS "empresa" (cnpj TEXT, identificador_matriz_filial BIGINT, razao_social TEXT, nome_fantasia TEXT, situacao_cadastral BIGINT, data_situacao_cadastral DATE, motivo_situacao_cadastral BIGINT, nome_cidade_exterior TEXT, codigo_natureza_juridica BIGINT, data_inicio_atividade DATE, cnae_fiscal BIGINT, descricao_tipo_logradouro TEXT, logradouro TEXT, numero TEXT, complemento TEXT, bairro TEXT, cep BIGINT, uf TEXT, codigo_municipio BIGINT, municipio TEXT, ddd_telefone_1 TEXT, ddd_telefone_2 TEXT, ddd_fax TEXT, qualificacao_do_responsavel BIGINT, capital_social NUMERIC, porte BIGINT, opcao_pelo_simples BOOLEAN, data_opcao_pelo_simples TEXT, data_exclusao_do_simples TEXT, opcao_pelo_mei BOOLEAN, situacao_especial TEXT, data_situacao_especial TEXT)', 'postgres://xxx:xx@yy.yy.yy.yy:5432/zzzz']
Reading schema:   0%|                         
```

**Comment by turicas** [comment]
O comando `rows pgimport` usa o cliente `psql` para se conectar ao PostgreSQL e fazer a transferência dos dados utilizando o comando `COPY`. Para isso, o pacote [postgresql-client-common](https://packages.debian.org/sid/postgresql-client-common) precisa estar instalado (caso você use Debian ou distribuições baseadas nele).
