### ISSUE TITLE
Erro ai extrair arquivos

### ISSUE THREAD

**Issue by fabianosanttana** [turicas/socios-brasil#53]
Opa, não sei se fiz algo errado, mas está dando esse erro, estou executando e,

Estou executando em macOS 11.5 (20G71)
`PS /Users/fabianosilva/Desktop/socios-brasil> python --version
Python 2.7.16`

`Extracting data/download/DADOS_ABERTOS_CNPJ_01.zip: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "extract_dump.py", line 369, in <module>
    main()
  File "extract_dump.py", line 364, in main
    censorship=censorship,
  File "extract_dump.py", line 297, in extract_files
    output_writers[row_type].writerow(row)
  File "/Users/fabianosilva/Library/Python/2.7/lib/python/site-packages/rows/utils.py", line 618, in writerow
    self.writer = csv.DictWriter(self.fobj, fieldnames=list(row.keys()))
  File "/Users/fabianosilva/Library/Python/2.7/lib/python/site-packages/rows/utils.py", line 611, in fobj
    self.filename_or_fobj, mode="w", encoding=self.encoding
  File "/Users/fabianosilva/Library/Python/2.7/lib/python/site-packages/rows/utils.py", line 464, in open_compressed
    fobj = gzip.GzipFile(filename, mode=mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
TypeError: coercing to Unicode: need string or buffer, PosixPath found
PS /Users/fabianosilva/Desktop/socios-brasil> `

**Comment by guigomesa** [comment]
Esse erro pode estar ligado a versão do Python, o script depende de libs do python 3.7.

Tente rodar nessa versão pode ser que resolva
